apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xkomoplane.platform.jlasut.io
  labels:
    type: platform
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: platform.jlasut.io/v1alpha1
    kind: XKomoplane
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        patchSets:
          - name: Common
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.labels
                toFieldPath: metadata.labels
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.annotations
                toFieldPath: metadata.annotations
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
        resources:
          - name: releaseKomoplane
            base:
              apiVersion: helm.crossplane.io/v1beta1
              kind: Release
              spec:
                forProvider:
                  chart:
                    name: komoplane
                    repository: https://helm-charts.komodor.io
                  namespace: komoplane-system
                  values:
                    ingress:
                      enabled: true
                      hosts:
                        - host: komoplane.127.0.0.1.nip.io
                          paths:
                            - path: /
                              pathType: Prefix
                    autoscaling:
                      enabled: true
                      minReplicas: 1
                      maxReplicas: 3
            patches:
              - type: PatchSet
                patchSetName: Common
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.operators.komoplane.version
                toFieldPath: spec.forProvider.chart.version
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.operators.komoplane.hostname
                toFieldPath: spec.forProvider.values.ingress.hosts[0].host
